### ISSUE TITLE
Sublime Cursor Jumping

### ISSUE THREAD

**Issue by retractedhack** [emmetio/livestyle-sublime-old#22] opened 2013-08-08 14:31 UTC
When I'm trying to type in Sublime Text 2 I run into an odd issue; the document will "blink" and then my cursor and the line I was typing will jump down to the last line of my document. If I hit Undo a few times it brings me back to my original location.  This issue didn't happen 100% of the time, but a bit too often for me to continue using it.  Otherwise it really is great work. Thanks!

**Comment by matchbranding** [comment] 2013-08-08 17:51
I have a similar experience happening.  Whenever I change anything in devtools it causes my cursor to jump to the top of the Sublime  Text 2 stylesheet.  Likewise when I edit in Sublime it creates a "blink" effect in the browser.

**Comment by sergeche** [comment] 2013-08-08 21:12
@retracted do you have any other tool/extension that may modify CSS stylesheet? It looks like something changes your CSS in browser, LiveStyle detects it and tries to update editor accordingly.

@matchbranding as per DevTools→editor editing issue: currently, LiveStyle just replaces content in editor but not highlights updated part. I’ll fix this issue for next update: https://github.com/emmetio/livestyle-sublime/issues/4

A good way to start debugging “blinking“ issue is to enable `debug` mode for LiveStyle: https://github.com/emmetio/livestyle-sublime/blob/master/LiveStyle.sublime-settings#L10 With this option enabled, all LiveStyle actions will be logged into console. When you’re typing in editor, LS should log something like `Run diff`. If it shows something like `Updating CSS ...` during _typing_, then my assumptions about background tool are correct.

**Comment by retractedhack** [comment] 2013-08-09 03:41
Most recently, the last thing that logged was 
--Emmet LiveStyle: [{"path":[[".room-booking-box label .label",1]],"action":"update","properties":[{"name":"font-weight","value":"normal","index":8}],"removed":[]}]--

While typing I get logs of "Emmet LiveStyle: Run diff" and "Emmet LiveStyle: []" back and forth.

Packages I have installed (from the Remove Packages list): ColdFusion, Emmet, ExpressionEngine, jQuery, LiveStyle, Package Control, Prefixr, PyV8, SCSS, and Tag.

Also, this last time I was typing a font-family stack and mis-typed "sans-serif" which is when it bumped me to the last line of my document.

**Comment by sergeche** [comment] 2013-08-15 22:15
Just pushed update, it might fix this issue.
PS: make sure your Chrome extension is updated too to at least 0.8.0.816 version. Otherwise package won’t work.

**Comment by sergeche** [comment] 2013-08-21 19:43
@retracted  did recent LiveStyle version solved this issue?

**Comment by retractedhack** [comment] 2013-08-21 20:02
@sergeche  For the most part.  It still happens some, but not nearly as often.

**Comment by sergeche** [comment] 2013-08-21 20:04
@retracted could you record a small screencast with this bug?

**Comment by Spetnik** [comment] 2013-08-21 23:34
I'm having this too (latest version). Can't seem to replicate it at the moment, but it seems to happen when typing quickly. If I undo and then type the same thing slowly, it doesn't jump. If I undo again and type it quickly it jumps.

A few times it's happened when editing a px value (e.g. changing 248px to 246px by placing the cursor after the "4", hitting backspace, and immediately typing "6" - or something similar to that effect).

I will try to record a screencast the next time it happens.

AJS

**Comment by Spetnik** [comment] 2013-08-21 23:55
It just happened. It didn't jump across the file like it sometimes does, but my css value got erased as I was typing. See http://www.youtube.com/watch?v=shvmG4l5Rjs (I slowed down the video) - I had typed "margin: 2px 0px " and then tried typing "10px" and this is what happened.

**Comment by jpotterm** [comment] 2013-08-22 02:20
This is also happening to me. It seems to happen at random times, and I cannot produce it consistently. I enabled debug mode and looked at the console output. Whenever it happens something like this is displayed in the console: http://pastebin.com/ct3RQtfr. It looks (to my untrained eye) like it's receiving a change from the chrome inspector, but I haven't made any changes there, so I don't know what's triggering it. I'm using the latest version of Chrome and I have the following extensions installed:
- PageSpeed Insights (by Google) 2.0.3.3
- LastPass 2.5.3
- JSONView 0.0.32
- Emmet LiveStyle 0.8.1.819
- Adblock Plus 1.5.4

Let me know if you need any more information. I'd really like to debug this because this issue makes LiveStyle basically unusable, and it's such an awesome plugin.

**Comment by jpotterm** [comment] 2013-08-22 02:24
This also brings up a feature I think would be useful. Can we have a way to indicate that we only want one-way patching (i.e. from Sublime -> Chrome) instead of two-way patching via some sort of setting? It can be unnerving to have things automatically inserted into your CSS file without double checking to see that they are inserted correctly.

**Comment by Spetnik** [comment] 2013-08-22 10:18
I totally agree with @jpotterm - I would NEVER want changes from the chrome inspector injected into my CSS file.

**Comment by jpotterm** [comment] 2013-08-22 18:56
I thought this might be caused by one of the extensions I had installed, so I disabled all extensions (besides LiveStyle) and this still happens. So I think we can rule out other browser extensions.

**Comment by sergeche** [comment] 2013-08-22 22:25
@jpotterm according to your log, something changed property in `.versions-lightbox .submit-button` selector. Is it possible that some JS script on your page did that?

**Comment by sergeche** [comment] 2013-08-23 14:49
One more question: did anyone enabled Chrome Workspaces?

**Comment by jpotterm** [comment] 2013-08-23 17:53
@sergeche I think it's highly unlikely that any javascript on the page changed styles for that class. For one thing, I was editing in sublime at the time, and I don't think I have any scripts that make changes without being fired by user events. For another thing, my code isn't even using that button at the moment, it's just a placeholder. Also, if JS were to change the style attribute of that element, would that trigger a reload? I thought only styles applied to classes (not elements) were brought over to sublime. And I didn't know there was even a way to do that through JS.

The only thing I could think of is that that button is inside of a Colorbox lightbox, so it's possible that Colorbox changed some styles, but that sounds pretty unlikely to me.

I don't see a Workspaces tab in my DevTools settings. Has that feature been removed?

**Comment by jpotterm** [comment] 2013-08-23 17:58
Also, I think `.versions-lightbox .submit-button` is the rule I was editing at the time. I don't remember for sure, but now that I understand the log better, I'll try to look for a pattern there.

It looks like the "message received" data is truncated. Is there a way to see the full message and figure out exactly what style it thinks was changed?

**Comment by sergeche** [comment] 2013-08-23 19:57
@jpotterm can you send me a full console log (in debug mode) whenever this error occurs next time?

**Comment by jpotterm** [comment] 2013-08-23 20:15
@sergeche what do you mean by a full log? I think I sent a complete transcript of the relevant portions. Or do you want every event since I've opened Sublime? Like I said, it looks like the message is truncated, but that's how it appears in the Sublime console, I didn't truncate it.

**Comment by sergeche** [comment] 2013-08-23 21:15
Yes, I need a complete log with every single event

**Comment by jpotterm** [comment] 2013-08-26 21:12
Ok, here is the complete log from right after it happened: http://pastebin.com/XsL7EA3W. I hope that helps! I re-enabled my browser extensions, since it happened even with them disabled (it seemed to happen slightly less frequently, but that could have been mental or coincidental.)

**Comment by bfa** [comment] 2013-08-27 19:00
Happening for me too, I'm using ST2 on Mac OS X 10.7.5.

**Comment by bfa** [comment] 2013-08-27 19:06
Here's a screencast of the issue happening on my machine. Notice the jump at 0:14 and 0:35. http://cl.ly/0x3h3T3z1r15

**Comment by sergeche** [comment] 2013-08-30 12:48
Just pushed v0.8.2 of Chrome extension, let me know if solves this issue.
If it still “jumps”: check if you have the same editor file is associated with multiple browser files in LiveStyle panel.

**Comment by jpotterm** [comment] 2013-08-30 18:14
I'll play around with it a little bit and let you know if this still happens. Thanks!

**Comment by jpotterm** [comment] 2013-09-03 13:43
This hasn't happened to me since you pushed that fix. So I think at least as far as I'm concerned this is fixed. Maybe a few other people who were having the problem can comment also as to whether or not that fix worked for them. Thanks!

**Comment by retractedhack** [comment] 2013-09-06 03:56
Also haven't noticed it at all.

**Comment by sergeche** [comment] 2013-09-06 10:32
OK, closing this issue

**Closed as completed by sergeche** 2013-09-06 10:32 UTC
