### ISSUE TITLE
repeating directives messes up the parser

### ISSUE THREAD

**Issue by cmpscabral** [emmetio/livestyle-sublime-old#21] opened 2013-08-08 13:00 UTC
Consider the following, I'm editing a css file in Sublime:
# someElement {

color:red;
color:blue;
}

If I remove the second line, LiveStyle updates Chrome but with no "color" styles. Making a simple change (delete undelete a line) brings back the correct styles

(not sure if I'm making myself clear, please ask any questions you need)

**Comment by sergeche** [comment] 2013-08-08 19:29
Well, technically, it’s not a bug since you can’t have two properties with the same name in one rule. But this is vital for vendor-prefixes support.

I’m closing this issue now because it will be fixed as a part of vendor-prefixes feature: https://github.com/emmetio/livestyle-sublime/issues/2

**Closed as completed by sergeche** 2013-08-08 19:29 UTC

**Comment by cmpscabral** [comment] 2013-08-08 19:51
great, thanks :)
